-- kalau pertama kali buat user dulu (login pakai system)
-- create user kp identified by kp;
-- GRANT CREATE SESSION to kp;
-- GRANT CONNECT, RESOURCE, CREATE USER, CREATE VIEW, CREATE SYNONYM, UNLIMITED TABLESPACE TO kp WITH ADMIN OPTION;

--untuk connect 
--conn kp/kp;

DROP TABLE LAMPIRAN;
DROP TABLE KOMPLAINB;
DROP TABLE KOMPLAINA;
DROP TABLE SUB_TOPIK2;
DROP TABLE SUB_TOPIK1;
DROP TABLE TOPIK;
DROP TABLE USERS;
DROP TABLE DIVISI;
DROP TABLE HAK_AKSES;


CREATE TABLE DIVISI
(
    KODE_DIVISI VARCHAR2(2) PRIMARY KEY,
    NAMA_DIVISI VARCHAR2(20)
);
CREATE TABLE HAK_AKSES
(
    KODE_HAK_AKSES VARCHAR2(1) PRIMARY KEY,
    NAMA_HAK_AKSES VARCHAR2(20)
);
CREATE TABLE USERS
(
    --buat sendiri
    NOMOR_INDUK VARCHAR2(8) PRIMARY KEY,
    PASSWORD VARCHAR2(200),
    NAMA VARCHAR2(30),
    KODE_HAK_AKSES VARCHAR2(1) REFERENCES HAK_AKSES(KODE_HAK_AKSES),
    EMAIL VARCHAR2(40) NULL,
    KODE_DIVISI VARCHAR2(2) REFERENCES DIVISI(KODE_DIVISI),
    KODE_ATASAN VARCHAR2(8) NULL
    --REFERENCES NOMOR INDUK ATASAN
);
CREATE TABLE TOPIK
(
    TOPIK VARCHAR2(20) NOT NULL,
    KODE_TOPIK VARCHAR2(5) PRIMARY KEY,
    DESKRIPSI VARCHAR2(200) NOT NULL,
    AU VARCHAR2(1) NOT NULL,
    DIV_TUJUAN VARCHAR2(2) REFERENCES DIVISI(KODE_DIVISI),
    NAMA VARCHAR2(50)
);

CREATE TABLE SUB_TOPIK1
(
    KODE_TOPIK VARCHAR2(5) REFERENCES TOPIK(KODE_TOPIK),
    SUB_TOPIK1 VARCHAR2(4) PRIMARY KEY,
    DESKRIPSI VARCHAR2(200)
);

CREATE TABLE SUB_TOPIK2
(
    KODE_TOPIK VARCHAR2(5) REFERENCES TOPIK(KODE_TOPIK),
    SUB_TOPIK1 VARCHAR2(4) REFERENCES SUB_TOPIK1(SUB_TOPIK1),
    SUB_TOPIK2 VARCHAR2(4) PRIMARY KEY,
    DESKRIPSI VARCHAR2(200),
    AKTIF VARCHAR2(1)
);

CREATE TABLE KOMPLAINA
(
    NO_KOMPLAIN VARCHAR2(10) PRIMARY KEY,
    TOPIK VARCHAR2(5) REFERENCES TOPIK(KODE_TOPIK),
    SUB_TOPIK1 VARCHAR2(4) REFERENCES SUB_TOPIK1(SUB_TOPIK1),
    SUB_TOPIK2 VARCHAR2(4) REFERENCES SUB_TOPIK2(SUB_TOPIK2),
    TGL_KEJADIAN DATE,
    TGL_TERBIT DATE,
    TGL_VERIFIKASI DATE,
    USER_VERIFIKASI VARCHAR2(8),
    TGL_CANCEL DATE,
    USER_CANCEL VARCHAR2(8),
    TGL_BANDING DATE,
    USER_BANDING VARCHAR2(8),
    TGL_VALIDASI DATE,
    USER_VALIDASI VARCHAR2(8),
    PENUGASAN VARCHAR2(8),
    STATUS VARCHAR2(6),
    TGL_PENANGANAN DATE,
    USER_PENANGANAN VARCHAR2(8),
    TGL_DEADLINE DATE,
    TGL_DONE DATE,
    USER_DONE VARCHAR2(8),
    USER_PENERBIT VARCHAR2(8)
);
--open, close, pending, cancel

CREATE TABLE KOMPLAINB --untuk feedback
(
    NO_KOMPLAIN VARCHAR2(4) REFERENCES KOMPLAINA(NO_KOMPLAIN),
    DESKRIPSI_MASALAH VARCHAR2(1000) NOT NULL,
    AKAR_MASALAH VARCHAR2(1000),
    T_KOREKTIF VARCHAR2(1000),
    T_PREVENTIF VARCHAR2(1000),
    KEBERATAN VARCHAR2(1000) 
);
-- NEW lokasi file untuk insert lampiran feedback

CREATE TABLE LAMPIRAN
(
    KODE_LAMPIRAN VARCHAR2(40) PRIMARY KEY,
    NO_KOMPLAIN VARCHAR2(4) REFERENCES KOMPLAINA(NO_KOMPLAIN),
    TANGGAL DATE,
    TIPE VARCHAR(1) --0 untuk komplain, 1 untuk feedback
);


--DML 
INSERT INTO DIVISI
VALUES('01', 'IT');
INSERT INTO DIVISI
VALUES('02', 'PRODUKSI');
INSERT INTO DIVISI
VALUES('03', 'VARIASI');
INSERT INTO DIVISI
VALUES('04', 'COR');
INSERT INTO DIVISI
VALUES('05', 'MARKETING');
INSERT INTO DIVISI
VALUES('06', 'ARESO');
--ada end_user, manager, direktur, admin
INSERT INTO HAK_AKSES
VALUES('1', 'End User');
INSERT INTO HAK_AKSES
VALUES('2', 'Manager');
INSERT INTO HAK_AKSES
VALUES('3', 'General Manager');
INSERT INTO HAK_AKSES
VALUES('4', 'Admin');

INSERT into users
values('12345678', '$2y$10$iAaeo2TCryN5.2rSPMAPB.bW0DrmhDbxQBR4zPoRYnGiFL30R96Rm', 'Enrico', '1', 'enrico@ubslinux.com', '01', '');
INSERT into users
values('12345679', '$2y$10$iAaeo2TCryN5.2rSPMAPB.bW0DrmhDbxQBR4zPoRYnGiFL30R96Rm', 'Enrico', '2', 'enricomanager@ubslinux.com', '01', '');
INSERT into users
values('12345680', '$2y$10$RGptyEa7CBK370RNA60NzeliRWjl6PlzyJJGQZyRAsAlhcBoUErBy', 'Ester', '1', 'ester@ubslinux.com', '01', '');
INSERT into users
values('12345681', '$2y$10$RGptyEa7CBK370RNA60NzeliRWjl6PlzyJJGQZyRAsAlhcBoUErBy', 'Ester', '2', 'estermanager@ubslinux.com', '01', '');
INSERT into users
values('admin', '$2y$10$P7qa.IhncGTaPfIiEG/MseX.MXjogMckU5WCWmLq8elUMNrfdCseS', 'Admin', '4', 
'admin1@ubslinux.com', '01', '');

INSERT INTO TOPIK values('ENVIRONMENT', 'E2301', 'Lingkungan', 'T', '01', 'Lingkungan');
INSERT INTO TOPIK values('MORALE', 'M2301', 'Moral', 'T', '01', 'Moral');
INSERT INTO TOPIK values('QUALITY', 'Q2301', 'Kualitas', 'T', '01', 'Kualitas');
INSERT INTO TOPIK values('SAFETY', 'S2301', 'Keamanan', 'T', '01', 'Keamanan');
INSERT INTO TOPIK values('PRODUCT', 'P2301', 'Produk', 'T', '01', 'Produk');
INSERT INTO TOPIK values('COST', 'C2301', 'Biaya', 'T', '01', 'Biaya');

COMMIT;
