-- kalau pertama kali buat user dulu (login pakai system)
-- create user kp identified by kp;
-- GRANT CREATE SESSION to kp;
-- GRANT CONNECT, RESOURCE, CREATE USER, CREATE VIEW, CREATE SYNONYM, UNLIMITED TABLESPACE TO kp WITH ADMIN OPTION;

--untuk connect 
--conn kp/kp;

DROP TABLE LAMPIRAN;
DROP TABLE KOMPLAINB;
DROP TABLE KOMPLAINA;
DROP TABLE SUB_TOPIK2;
DROP TABLE SUB_TOPIK1;
DROP TABLE TOPIK;
DROP TABLE USERS;
DROP TABLE DIVISI;
DROP TABLE HAK_AKSES;


CREATE TABLE DIVISI
(
    KODEDIV VARCHAR2(2) PRIMARY KEY,
    NAMA VARCHAR2(20), 
    AKTIF VARCHAR2(1),
    KEL_SAH VARCHAR2(2) 
);
CREATE TABLE HAK_AKSES
(
    KODE_HAK_AKSES VARCHAR2(1) PRIMARY KEY,
    NAMA_HAK_AKSES VARCHAR2(20)
);
CREATE TABLE USERS
(
    --buat sendiri
    NOMOR_INDUK VARCHAR2(8) PRIMARY KEY,
    PASSWORD VARCHAR2(200),
    NAMA VARCHAR2(30),
    KODE_HAK_AKSES VARCHAR2(1),
    EMAIL VARCHAR2(40) NULL,
    KODEDIV VARCHAR2(2) REFERENCES DIVISI(KODEDIV),
    KODE_ATASAN VARCHAR2(8) NULL 
);
CREATE TABLE TOPIK
(
    TOPIK VARCHAR2(20) NOT NULL,
    KODE_TOPIK VARCHAR2(5) PRIMARY KEY,
    DESKRIPSI VARCHAR2(200) NOT NULL,
    AU VARCHAR2(1) NOT NULL,
    DIV_TUJUAN VARCHAR2(2) REFERENCES DIVISI(KODEDIV),
    NAMA VARCHAR2(50)
);

CREATE TABLE SUB_TOPIK1
(
    KODE_TOPIK VARCHAR2(5) REFERENCES TOPIK(KODE_TOPIK),
    SUB_TOPIK1 VARCHAR2(4),
    DESKRIPSI VARCHAR2(200)
);

ALTER TABLE SUB_TOPIK1
ADD CONSTRAINT PK_SUB_TOPIK1
PRIMARY KEY (KODE_TOPIK, SUB_TOPIK1);

CREATE TABLE SUB_TOPIK2
(
    KODE_TOPIK VARCHAR2(5) REFERENCES TOPIK(KODE_TOPIK),
    SUB_TOPIK1 VARCHAR2(4),
    SUB_TOPIK2 VARCHAR2(4),
    DESKRIPSI VARCHAR2(200),
    AKTIF VARCHAR2(1)
);
ALTER TABLE SUB_TOPIK2
ADD CONSTRAINT PK_SUB_TOPIK2
PRIMARY KEY (KODE_TOPIK, SUB_TOPIK1, SUB_TOPIK2);

CREATE TABLE KOMPLAINA
(
    NO_KOMPLAIN VARCHAR2(10) PRIMARY KEY,
    TOPIK VARCHAR2(5) REFERENCES TOPIK(KODE_TOPIK),
    SUB_TOPIK1 VARCHAR2(4),
    SUB_TOPIK2 VARCHAR2(4),
    TGL_KEJADIAN DATE,
    TGL_TERBIT DATE,
    TGL_VERIFIKASI DATE NULL,
    USER_VERIFIKASI VARCHAR2(8) NULL,
    TGL_CANCEL DATE NULL,
    USER_CANCEL VARCHAR2(8) NULL,
    TGL_BANDING DATE NULL,
    USER_BANDING VARCHAR2(8) NULL,
    TGL_VALIDASI DATE NULL,
    USER_VALIDASI VARCHAR2(8) NULL,
    PENUGASAN VARCHAR2(8) NULL,
    STATUS VARCHAR2(6),
    TGL_PENANGANAN DATE NULL,
    USER_PENANGANAN VARCHAR2(8) NULL,
    TGL_DEADLINE DATE NULL,
    TGL_DONE DATE NULL,
    USER_DONE VARCHAR2(8) NULL,
    USER_PENERBIT VARCHAR2(8) 
);
--open, close, pending, cancel

CREATE TABLE KOMPLAINB --untuk feedback
(
    NO_KOMPLAIN VARCHAR2(10) REFERENCES KOMPLAINA(NO_KOMPLAIN),
    DESKRIPSI_MASALAH VARCHAR2(1000) NOT NULL,
    AKAR_MASALAH VARCHAR2(1000),
    T_KOREKTIF VARCHAR2(1000),
    T_PREVENTIF VARCHAR2(1000),
    KEBERATAN VARCHAR2(1000) 
); 
CREATE TABLE LAMPIRAN
(
    KODE_LAMPIRAN VARCHAR2(40) PRIMARY KEY,
    NO_KOMPLAIN VARCHAR2(10) REFERENCES KOMPLAINA(NO_KOMPLAIN),
    TANGGAL DATE,
    TIPE VARCHAR(1) --0 untuk komplain, 1 untuk feedback
);


--DML MENYESUAIKAN SCRIPT LAINNYA

COMMIT; 
